# Generated by Django 6.0.4 on 2026-04-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
