# Generated by Django 6.0.4 on 2026-04-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='images',
        ),
    ]
